version: 2
updates:
  - package-ecosystem: gomod
    directory: /internal
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /services/api
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /services/worker
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
