apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-worker
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-worker
  template:
    metadata:
      labels:
        app: inventory-worker
    spec:
      containers:
        - name: inventory-worker
          image: ecommerce/inventory-worker:local
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: MONGO_URI
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: MONGO_DB_INVENTORY
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: RABBITMQ_URL
