apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - infrastructure/mongo.yaml
  - infrastructure/mysql.yaml
  - infrastructure/redis.yaml
  - infrastructure/rabbitmq.yaml
  - apps/auth-service.yaml
  - apps/inventory-service.yaml
  - apps/inventory-worker.yaml
  - apps/product-service.yaml
  - apps/payment-service.yaml
  - apps/order-service.yaml
  - apps/order-worker.yaml
  - apps/notification-service.yaml
  - apps/api-gateway.yaml

images:
  - name: ecommerce/api-gateway
    newTag: local
  - name: ecommerce/auth-service
    newTag: local
  - name: ecommerce/inventory-service
    newTag: local
  - name: ecommerce/inventory-worker
    newTag: local
  - name: ecommerce/product-service
    newTag: local
  - name: ecommerce/payment-service
    newTag: local
  - name: ecommerce/order-service
    newTag: local
  - name: ecommerce/order-worker
    newTag: local
  - name: ecommerce/notification-service
    newTag: local
