apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  JWT_SECRET: dev-secret-change-me
  MYSQL_ROOT_PASSWORD: root
  MYSQL_PASSWORD: app
  MYSQL_USER: app
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
