syntax = "proto3";

package payment;

option go_package = "github.com/kaungmyathan18/golang-ecommerce-microservice/proto/payment/pb";

service PaymentService {
  rpc InitiatePayment(InitiatePaymentRequest) returns (InitiatePaymentResponse);
  rpc GetPayment(GetPaymentRequest) returns (GetPaymentResponse);
}

message InitiatePaymentRequest {
  string order_id = 1;
  string user_id = 2;
  double amount = 3;
}

message InitiatePaymentResponse {
  string payment_id = 1;
  string order_id = 2;
  string status = 3;
}

message GetPaymentRequest {
  string payment_id = 1;
}

message GetPaymentResponse {
  string payment_id = 1;
  string order_id = 2;
  string user_id = 3;
  double amount = 4;
  string status = 5;
}
